=== KozinOleg97/Lab_XML_2/src/main/resources/testXML/TestXSD.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://lab.kozin.rsatu.ru/"
           xmlns="http://lab.kozin.rsatu.ru/"
           elementFormDefault="qualified">


    <xs:complexType name="man">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="patronim" type="xs:string"/>
            <xs:element name="dateOfBirth" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="employee">
        <xs:complexContent>
            <xs:extension base="man">
                <xs:sequence>
                    <xs:element name="employeeDoc" type="doc"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="student">
        <xs:complexContent>
            <xs:extension base="man">
                <xs:sequence>
                    <xs:element name="studentDoc" type="doc"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="doc">
        <xs:sequence>
            <xs:element name="docID" type="id"/>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="id">
        <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="9"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="department">
        <xs:sequence>
            <xs:element name="departmentName" type="xs:string"/>
            <xs:element name="boss" minOccurs="1" maxOccurs="5" type="employee"/>
            <xs:element name="departmentEmployee" minOccurs="1" maxOccurs="500" type="employee"/>
            <!-- <xs:element name="subsidiaries" minOccurs="0" maxOccurs="100" type="department"/>-->
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="administration">
        <xs:complexContent>
            <xs:extension base="department">
                <xs:sequence>
                    <xs:element name="bookkeeping" type="bookkeeping"/>
                    <xs:element name="departmentOfScientific" type="departmentOfScientific"/>
                    <xs:element name="economicDepartment" type="economicDepartment"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="bookkeeping">
        <xs:complexContent>
            <xs:extension base="department">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="economicDepartment">
        <xs:complexContent>
            <xs:extension base="department">
                <xs:sequence>
                    <xs:element name="cafe" type="department"/>
                    <xs:element name="staffDepartment" type="department"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="departmentOfScientific">
        <xs:complexContent>
            <xs:extension base="department">
                <xs:sequence>
                    <xs:element name="library" type="library"/>
                    <xs:element name="educationalMethodicalDepartment" type="department"/>
                    <xs:element name="faculty" type="faculty" minOccurs="2" maxOccurs="50"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="library">
        <xs:complexContent>
            <xs:extension base="department">

                <xs:sequence minOccurs="10" maxOccurs="unbounded">
                    <xs:element name="book" type="book"/>
                </xs:sequence>

            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="book">
        <xs:sequence>
            <xs:element name="bookID" type="id"/>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="state" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="faculty">
        <xs:sequence>
            <xs:element name="facultyName" type="xs:string"/>
            <xs:element name="dean" type="employee"/>
            <xs:element name="kafedra" type="kafedra"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="kafedra">
        <xs:sequence>
            <xs:element name="kafedraName" type="xs:string"/>
            <xs:element name="headTeacher" type="employee"/>
            <xs:element name="teacher" type="employee" minOccurs="2" maxOccurs="50"/>
            <xs:element name="group" type="group" minOccurs="2" maxOccurs="50"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="group">
        <xs:sequence>
            <xs:element name="groupName" type="xs:string"/>
            <xs:element name="year" type="xs:gYear"/>
            <xs:element name="starosta" type="student"/>
            <xs:element name="students" type="student" minOccurs="5" maxOccurs="70"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="administration" type="administration"/>


            </xs:sequence>
            <xs:attribute name="universityName" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KozinOleg97/Lab_XML_2/src/main/resources/testXML/NewGen.xml
<university
        xmlns="http://example.com/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/ TestXSD.xsd"
        universityName="str1234">
    <administration>
        <departmentName>string</departmentName>
        <!--1 to 5 repetitions:-->
        <boss>
            <name>string</name>
            <surname>string</surname>
            <patronim>string</patronim>
            <dateOfBirth>2008-09-29</dateOfBirth>
            <employeeDoc>
                <docID>201</docID>
            </employeeDoc>
        </boss>
        <!--1 to 500 repetitions:-->
        <departmentEmployee>
            <name>string</name>
            <surname>string</surname>
            <patronim>string</patronim>
            <dateOfBirth>2014-09-19</dateOfBirth>
            <employeeDoc>
                <docID>201</docID>
            </employeeDoc>
        </departmentEmployee>
        <bookkeeping>
            <departmentName>string</departmentName>
            <!--1 to 5 repetitions:-->
            <boss>
                <name>string</name>
                <surname>string</surname>
                <patronim>string</patronim>
                <dateOfBirth>2006-08-19+04:00</dateOfBirth>
                <employeeDoc>
                    <docID>201</docID>
                </employeeDoc>
            </boss>
            <!--1 to 500 repetitions:-->
            <departmentEmployee>
                <name>string</name>
                <surname>string</surname>
                <patronim>string</patronim>
                <dateOfBirth>2009-05-16</dateOfBirth>
                <employeeDoc>
                    <docID>201</docID>
                </employeeDoc>
            </departmentEmployee>
        </bookkeeping>
        <departmentOfScientific>
            <departmentName>string</departmentName>
            <!--1 to 5 repetitions:-->
            <boss>
                <name>string</name>
                <surname>string</surname>
                <patronim>string</patronim>
                <dateOfBirth>2003-08-09+04:00</dateOfBirth>
                <employeeDoc>
                    <docID>201</docID>
                </employeeDoc>
            </boss>
            <!--1 to 500 repetitions:-->
            <departmentEmployee>
                <name>string</name>
                <surname>string</surname>
                <patronim>string</patronim>
                <dateOfBirth>2012-09-13+04:00</dateOfBirth>
                <employeeDoc>
                    <docID>201</docID>
                </employeeDoc>
            </departmentEmployee>
            <library>
                <departmentName>string</departmentName>
                <!--1 to 5 repetitions:-->
                <boss>
                    <name>string</name>
                    <surname>string</surname>
                    <patronim>string</patronim>
                    <dateOfBirth>2009-10-14</dateOfBirth>
                    <employeeDoc>
                        <docID>201</docID>
                    </employeeDoc>
                </boss>
                <!--1 to 500 repetitions:-->
                <departmentEmployee>
                    <name>string</name>
                    <surname>string</surname>
                    <patronim>string</patronim>
                    <dateOfBirth>2010-03-18</dateOfBirth>
                    <employeeDoc>
                        <docID>201</docID>
                    </employeeDoc>
                </departmentEmployee>
                <!--You have a CHOICE of the next 2 items at this level-->
                <book>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>true</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>true</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>false</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>false</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>true</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>false</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>false</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>false</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>false</state>
                    <bookID>201</bookID>
                    <title>string</title>
                    <state>true</state>
                </book>
            </library>
            <educationalMethodicalDepartment>
                <departmentName>string</departmentName>
                <!--1 to 5 repetitions:-->
                <boss>
                    <name>string</name>
                    <surname>string</surname>
                    <patronim>string</patronim>
                    <dateOfBirth>2015-08-24</dateOfBirth>
                    <employeeDoc>
                        <docID>201</docID>
                    </employeeDoc>
                </boss>
                <!--1 to 500 repetitions:-->
                <departmentEmployee>
                    <name>string</name>
                    <surname>string</surname>
                    <patronim>string</patronim>
                    <dateOfBirth>2015-06-18+03:00</dateOfBirth>
                    <employeeDoc>
                        <docID>201</docID>
                    </employeeDoc>
                </departmentEmployee>
            </educationalMethodicalDepartment>
            <!--2 to 50 repetitions:-->
            <faculty>
                <facultyName>string</facultyName>
                <dean>
                    <name>string</name>
                    <surname>string</surname>
                    <patronim>string</patronim>
                    <dateOfBirth>2000-04-21+04:00</dateOfBirth>
                    <employeeDoc>
                        <docID>201</docID>
                    </employeeDoc>
                </dean>
                <kafedra>
                    <kafedraName>string</kafedraName>
                    <headTeacher>
                        <name>string</name>
                        <surname>string</surname>
                        <patronim>string</patronim>
                        <dateOfBirth>2017-04-19+03:00</dateOfBirth>
                        <employeeDoc>
                            <docID>201</docID>
                        </employeeDoc>
                    </headTeacher>
                    <!--2 to 50 repetitions:-->
                    <teacher>
                        <name>string</name>
                        <surname>string</surname>
                        <patronim>string</patronim>
                        <dateOfBirth>2008-08-06+04:00</dateOfBirth>
                        <employeeDoc>
                            <docID>201</docID>
                        </employeeDoc>
                    </teacher>
                    <teacher>
                        <name>string</name>
                        <surname>string</surname>
                        <patronim>string</patronim>
                        <dateOfBirth>2011-12-25</dateOfBirth>
                        <employeeDoc>
                            <docID>201</docID>
                        </employeeDoc>
                    </teacher>
                    <!--2 to 50 repetitions:-->
                    <group>
                        <groupName>string</groupName>
                        <year>2015+03:00</year>
                        <starosta>
                            <name>string</name>
                            <surname>string</surname>
                            <patronim>string</patronim>
                            <dateOfBirth>2018-07-19+03:00</dateOfBirth>
                            <studentDoc>
                                <docID>201</docID>
                            </studentDoc>
                        </starosta>
                        <!--5 to 70 repetitions:-->
                        <students>
                            <name>string</name>
                            <surname>string</surname>
                            <patronim>string</patronim>
                            <dateOfBirth>2004-12-06+03:00</dateOfBirth>
                            <studentDoc>
                                <docID>201</docID>
                            </studentDoc>
                        </students>
                        <students>
                            <name>string</name>
                            <surname>string</surname>
                            <patronim>string</patronim>
                            <dateOfBirth>2006-12-05</dateOfBirth>
                            <studentDoc>
                                <docID>201</docID>
                            </studentDoc>
                        </students>
                        <students>
                            <name>string</name>
                            <surname>string</surname>
                            <patronim>string</patronim>
                            <dateOfBirth>2016-09-11</dateOfBirth>
                            <studentDoc>
                                <docID>201</docID>
                            </studentDoc>
                        </students>
                        <students>
                            <name>string</name>
                            <surname>string</surname>
